# Generated by Django 3.2.6 on 2021-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_auction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['auction', 'date'], name='auctions_co_auction_111a33_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['date'], name='auctions_co_date_86232f_idx'),
        ),
    ]
